apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-audit-dev
  annotations:
    codefresh.io/product: octopub-audit
spec:
  project: default
  sources:
    - repoURL: https://github.com/kmccarthyy/octopub.git
      targetRevision: HEAD
      path: codefresh/helm/octopub-audits/dev        
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true